addins:
 - {name: SSF, 
    location: [[patch_embed, norm]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[patch_embed, norm]],
    hook: [[adapt_output_post, post]]}
 - {name: SSF, 
    location: [[blocks, 0, attn]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 0, attn, qkv]],
    hook: [[adapt_output, post]],
    kwargs: {'dim': 2304}}
 - {name: SSF, 
    location: [[blocks, 0, attn, proj_drop]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 0, mlp]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 0, mlp, act]],
    hook: [[adapt_input, pre]],
    kwargs: {'dim': 3072}}
 - {name: SSF, 
    location: [[blocks, 0, mlp, drop2]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 1, attn]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 1, attn, qkv]],
    hook: [[adapt_output, post]],
    kwargs: {'dim': 2304}}
 - {name: SSF, 
    location: [[blocks, 1, attn, proj_drop]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 1, mlp]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 1, mlp, act]],
    hook: [[adapt_input, pre]],
    kwargs: {'dim': 3072}}
 - {name: SSF, 
    location: [[blocks, 1, mlp, drop2]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 2, attn]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 2, attn, qkv]],
    hook: [[adapt_output, post]],
    kwargs: {'dim': 2304}}
 - {name: SSF, 
    location: [[blocks, 2, attn, proj_drop]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 2, mlp]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 2, mlp, act]],
    hook: [[adapt_input, pre]],
    kwargs: {'dim': 3072}}
 - {name: SSF, 
    location: [[blocks, 2, mlp, drop2]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 3, attn]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 3, attn, qkv]],
    hook: [[adapt_output, post]],
    kwargs: {'dim': 2304}}
 - {name: SSF, 
    location: [[blocks, 3, attn, proj_drop]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 3, mlp]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 3, mlp, act]],
    hook: [[adapt_input, pre]],
    kwargs: {'dim': 3072}}
 - {name: SSF, 
    location: [[blocks, 3, mlp, drop2]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 4, attn]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 4, attn, qkv]],
    hook: [[adapt_output, post]],
    kwargs: {'dim': 2304}}
 - {name: SSF, 
    location: [[blocks, 4, attn, proj_drop]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 4, mlp]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 4, mlp, act]],
    hook: [[adapt_input, pre]],
    kwargs: {'dim': 3072}}
 - {name: SSF, 
    location: [[blocks, 4, mlp, drop2]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 5, attn]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 5, attn, qkv]],
    hook: [[adapt_output, post]],
    kwargs: {'dim': 2304}}
 - {name: SSF, 
    location: [[blocks, 5, attn, proj_drop]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 5, mlp]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 5, mlp, act]],
    hook: [[adapt_input, pre]],
    kwargs: {'dim': 3072}}
 - {name: SSF, 
    location: [[blocks, 5, mlp, drop2]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 6, attn]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 6, attn, qkv]],
    hook: [[adapt_output, post]],
    kwargs: {'dim': 2304}}
 - {name: SSF, 
    location: [[blocks, 6, attn, proj_drop]],
    hook: [[adapt_input, pre]]}    
 - {name: SSF, 
    location: [[blocks, 6, mlp]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 6, mlp, act]],
    hook: [[adapt_input, pre]],
    kwargs: {'dim': 3072}}
 - {name: SSF, 
    location: [[blocks, 6, mlp, drop2]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 7, attn]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 7, attn, qkv]],
    hook: [[adapt_output, post]],
    kwargs: {'dim': 2304}}
 - {name: SSF, 
    location: [[blocks, 7, attn, proj_drop]],
    hook: [[adapt_input, pre]]}    
 - {name: SSF, 
    location: [[blocks, 7, mlp]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 7, mlp, act]],
    hook: [[adapt_input, pre]],
    kwargs: {'dim': 3072}}
 - {name: SSF, 
    location: [[blocks, 7, mlp, drop2]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 8, attn]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 8, attn, qkv]],
    hook: [[adapt_output, post]],
    kwargs: {'dim': 2304}}
 - {name: SSF, 
    location: [[blocks, 8, attn, proj_drop]],
    hook: [[adapt_input, pre]]}    
 - {name: SSF, 
    location: [[blocks, 8, mlp]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 8, mlp, act]],
    hook: [[adapt_input, pre]],
    kwargs: {'dim': 3072}}
 - {name: SSF, 
    location: [[blocks, 8, mlp, drop2]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 9, attn]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 9, attn, qkv]],
    hook: [[adapt_output, post]],
    kwargs: {'dim': 2304}}
 - {name: SSF, 
    location: [[blocks, 9, attn, proj_drop]],
    hook: [[adapt_input, pre]]}    
 - {name: SSF, 
    location: [[blocks, 9, mlp]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 9, mlp, act]],
    hook: [[adapt_input, pre]],
    kwargs: {'dim': 3072}}
 - {name: SSF, 
    location: [[blocks, 9, mlp, drop2]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 10, attn]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 10, attn, qkv]],
    hook: [[adapt_output, post]],
    kwargs: {'dim': 2304}}
 - {name: SSF, 
    location: [[blocks, 10, attn, proj_drop]],
    hook: [[adapt_input, pre]]}    
 - {name: SSF, 
    location: [[blocks, 10, mlp]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 10, mlp, act]],
    hook: [[adapt_input, pre]],
    kwargs: {'dim': 3072}}
 - {name: SSF, 
    location: [[blocks, 10, mlp, drop2]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 11, attn]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 11, attn, qkv]],
    hook: [[adapt_output, post]],
    kwargs: {'dim': 2304}}
 - {name: SSF, 
    location: [[blocks, 11, attn, proj_drop]],
    hook: [[adapt_input, pre]]}    
 - {name: SSF, 
    location: [[blocks, 11, mlp]],
    hook: [[adapt_input, pre]]}
 - {name: SSF, 
    location: [[blocks, 11, mlp, act]],
    hook: [[adapt_input, pre]],
    kwargs: {'dim': 3072}}
 - {name: SSF, 
    location: [[blocks, 11, mlp, drop2]],
    hook: [[adapt_input, pre]]}
 - {name: SSF,
    location: [[norm]],
    hook: [[adapt_output, post]]}

reuse_keys:
  - [addin]
  - [head]
  - [fc_norm]
