addins:
  - {
    name: VPT,
    location: [[blocks, 1], [blocks, 2], [blocks, 3], [blocks, 4], [blocks, 5], [blocks, 6], [blocks, 7], [blocks, 8], [blocks, 9],  [blocks, 10], [blocks, 11]],
    hook: [[cat_prompt_deep_1, pre], [cat_prompt_deep_2, pre], [cat_prompt_deep_3, pre], [cat_prompt_deep_4, pre], [cat_prompt_deep_5, pre], [cat_prompt_deep_6, pre], [cat_prompt_deep_7, pre], [cat_prompt_deep_8, pre], [cat_prompt_deep_9, pre], [cat_prompt_deep_10, pre], [cat_prompt_deep_11, pre]],
    }

vpt_initiation: random
vpt_project: -1
vpt_deep: true
vpt_dropout: 0.0
vpt_num_tokens: 3

reuse_keys:
  - [addin]
  - [head]
  - [fc_norm]
