addins:
  - {
    name: VQT,
    location: [[blocks, 0],[blocks, 0, attn],[blocks, 0], [blocks, 0, attn, proj], [blocks, 0, attn, qkv],
    [blocks, 1], [blocks, 1, attn],[blocks, 1], [blocks, 1, attn, proj], [blocks, 1, attn, qkv],
    [blocks, 2], [blocks, 2, attn],[blocks, 2], [blocks, 2, attn, proj], [blocks, 2, attn, qkv],
    [blocks, 3], [blocks, 3, attn],[blocks, 3], [blocks, 3, attn, proj], [blocks, 3, attn, qkv],
    [blocks, 4], [blocks, 4, attn],[blocks, 4], [blocks, 4, attn, proj], [blocks, 4, attn, qkv],
    [blocks, 5], [blocks, 5, attn],[blocks, 5], [blocks, 5, attn, proj], [blocks, 5, attn, qkv],
    [blocks, 6], [blocks, 6, attn],[blocks, 6], [blocks, 6, attn, proj], [blocks, 6, attn, qkv],
    [blocks, 7], [blocks, 7, attn],[blocks, 7], [blocks, 7, attn, proj], [blocks, 7, attn, qkv],
    [blocks, 8], [blocks, 8, attn],[blocks, 8], [blocks, 8, attn, proj], [blocks, 8, attn, qkv],
    [blocks, 9], [blocks, 9, attn],[blocks, 9], [blocks, 9, attn, proj], [blocks, 9, attn, qkv],
    [blocks, 10],[blocks, 10, attn],[blocks, 10],[blocks, 10, attn, proj], [blocks, 10, attn, qkv],
    [blocks, 11],[blocks, 11, attn],[blocks, 11],[blocks, 11, attn, proj], [blocks, 11, attn, qkv],
    [head]
    ],
    hook: [[cat_query_prompt_1_0, pre],[divide_query_prompt, pre],[get_query_output, post], [cat_query_prompt_2_0, pre], [get_query_prompt_0, post],
    [cat_query_prompt_1_1, pre],[divide_query_prompt, pre],[get_query_output, post], [cat_query_prompt_2_1, pre],[get_query_prompt_1, post], 
    [cat_query_prompt_1_2, pre],[divide_query_prompt, pre],[get_query_output, post], [cat_query_prompt_2_2, pre],[get_query_prompt_2, post],
    [cat_query_prompt_1_3, pre],[divide_query_prompt, pre],[get_query_output, post], [cat_query_prompt_2_3, pre],[get_query_prompt_3, post],
    [cat_query_prompt_1_4, pre],[divide_query_prompt, pre],[get_query_output, post], [cat_query_prompt_2_4, pre],[get_query_prompt_4, post],
    [cat_query_prompt_1_5, pre],[divide_query_prompt, pre],[get_query_output, post], [cat_query_prompt_2_5, pre],[get_query_prompt_5, post],
    [cat_query_prompt_1_6, pre],[divide_query_prompt, pre],[get_query_output, post], [cat_query_prompt_2_6, pre],[get_query_prompt_6, post], 
    [cat_query_prompt_1_7, pre],[divide_query_prompt, pre],[get_query_output, post], [cat_query_prompt_2_7, pre],[get_query_prompt_7, post],
    [cat_query_prompt_1_8, pre],[divide_query_prompt, pre],[get_query_output, post], [cat_query_prompt_2_8, pre],[get_query_prompt_8, post],
    [cat_query_prompt_1_9, pre],[divide_query_prompt, pre],[get_query_output, post], [cat_query_prompt_2_9, pre],[get_query_prompt_9, post],
    [cat_query_prompt_1_10, pre],[divide_query_prompt, pre],[get_query_output, post], [cat_query_prompt_2_10, pre],[get_query_prompt_10, post],
    [cat_query_prompt_1_11, pre],[divide_query_prompt, pre],[get_query_output, post], [cat_query_prompt_2_11, pre],[get_query_prompt_11, post],
    [make_logits, post]]
    }

vqt_pool_feats: false
vqt_weighted_sum_feats: false
vqt_norm_feats: true
vqt_dropout: 0.5
vqt_num_query_tokens: 3

reuse_keys:
  - [addin]
  - [head]
  - [fc_norm]
